### ISSUE TITLE
Convert visualisations to ggplot2

### ISSUE THREAD

**Issue by michbur** [jolars/SLOPE#21]
Functions to update:

- [x] plot.SLOPE
- [x] plot.TrainedSLOPE
- [x] plotDiagnostics
~~@michbur and @jakubkala will work on that.~~

**Comment by michbur** [comment]
@KrystynaGrzesiak, few things to consider:

 - updating imports,
 - adding tests.

**Comment by jolars** [comment]
Done through #22
