### ISSUE TITLE
Outputs of FISTA and ADMM don't match even after setting 'intercept=FALSE'

### ISSUE THREAD

**Issue by straw-boy** [jolars/SLOPE#8]
I came across the following test:

`set.seed(1)`
`n = 10`
`p = 20`
`d <- randomProblem(n,p,response="gaussian")`
`fit1 <- SLOPE(d$x, d$y,alpha=c(1,0.00),intercept=FALSE,verbosity=3)`
`fit2 <- SLOPE(d$x, d$y,alpha=c(1,0.00),solver="admm",intercept=FALSE,verbosity=3)`
`print(coef(fit1)-coef(fit2))`

Coefficients for `alpha=0` don't match. Output doesn't match in solvers package too when `alpha=c(1.0,0.005)
` which I am currently looking into. Seemed a critical issue for SLOPE package as well so I raised it. On a 10k feet view, duality gap is blowing up.

**Comment by jolars** [comment]
Good catch, thanks for reporting this! Do you have any idea which of the solvers is returning the correct output?

**Comment by straw-boy** [comment]
The outputs of SLOPE::SLOPE(solver="admm") and solvers::ADMM matched perfectly. So I believe problem ADMM is fine.

**Comment by jolars** [comment]
Actually, I don't think anything is wrong here at all. The only problem exists at `alpha = 0` but that's the completely unregularized solution and since `p > n` there is no unique solution to the problem, so I think this is actually not a problem.

**Comment by straw-boy** [comment]
As far as I remember, I think coefficients weren't matching for `alpha=c(1,0.005)` as well.

**Comment by jolars** [comment]
> As far as I remember, I think coefficients weren't matching for `alpha=c(1,0.005)` as well.

with `alpha = 0.005` the solvers do converge to the same solution, but precision differs a little based on the convergence criteria settings.
